# how to use python

## 哈希表

### 排序

In [25]:
# 将字典d按value的值进行排序
d = {'a': 24, 'g': 52, 'i': 12, 'k': 33}
b4 = sorted(d.items(), key=lambda x: x[1])
print(b4) 

"""sorted(d.items(), key=lambda x: x[1])   中 d.items() 为待排序的对象；
key=lambda x: x[1] 为对前面的对象中的第二维数据（即value）的值进行排序。 
key=lambda  变量：变量[维数] 。维数可以按照自己的需要进行设置。"""

# 将列表中的age由大到小排序
alist = [{'name1': 'a', 'age': 20}, {'name2': 'b', 'age': 30}, {'name3': 'c', 'age': 25}]
b = sorted(alist, key=lambda x: x['age'], reverse=True) # reverse 是否逆序
print(b)

[('i', 12), ('a', 24), ('k', 33), ('g', 52)]
[{'name2': 'b', 'age': 30}, {'name3': 'c', 'age': 25}, {'name1': 'a', 'age': 20}]


## class

### 1. 类的定义和语法

In [8]:
class dog(object): # 用class定义类
    "dog class" # 对类的说明
    
    def __init__(self, name): # 构造函数/构造方法/初始化方法
        self.name = name # 属性/成员变量/字段

    def sayhi(self): # 类方法/动态属性
        "sayhi function" # 对类方法的说明
        print("hello, I am a dog, my name is", self.name)

d = dog("AAA") # 定义一个d的对象（实例）
d.sayhi() # 调用实例的方法

hello, I am a dog, my name is AAA


### 2. self关键字

self相当于实例化对象本身d，在实例化过程中将自身传入

`d = dog(d, "AAA")`

### 3. 函数__init__(), \_\_del__()

在类中__init__()函数叫构造函数，又叫构造方法，也可以叫初始化函数。它的作用就是初始化实例时，初始化传入实例的的默认值。

在类中__del__()函数叫做析构函数，是在实例销毁的时候调用的函数。

### 4. 类的实例化过程图解

· 第一步：先申请一块空间，并命名实例

· 第二步：将地址和赋值参数传给类

· 第三步：生成实例

### 5. 访问类属性

### 6. 修改类属性

In [9]:
class dog(object):
    "dog class"
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def sayhi(self, update_age):
        self.age = update_age

d = dog("AAA", 18)
d.sayhi(19) # 在类的方法中修改
print(d.age)
d.age = 20 # 在类外面修改
print(d.age)

19
20


就是说在类的方法中或者类的外面都可以修改类的属性

### 7. 私有属性

In [13]:
class dog(object):
    "dog class"
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.__sex = "male" # 定义私有属性
    
    def sayhi(self, update_age):
        self.age = update_age

d = dog("AAA", 18)
print(d.__sex)

AttributeError: 'dog' object has no attribute '__sex'

私有属性是不可以访问的，更不可以修改

#### 强制访问/修改私有属性

In [16]:
class dog(object):
    "dog class"
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.__sex = "male" # 定义私有属性
    
    def sayhi(self, update_age):
        self.age = update_age

d = dog("AAA", 18)
print(d._dog__sex)
d._dog__sex = 'female'
print(d._dog__sex)

male
female


这种方法就更为暴力，可以访问也可以修改，就是：对象名._类名__属性名

#### get方法访问私有属性

In [14]:
class dog(object):
    "dog class"
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.__sex = "male"

    def get_sex(self): # 定义get方法
        return self.__sex # 返回

d = dog("AAA", 18)
d_sex = d.get_sex()
print(d_sex)

male


这种方法只能访问私有属性，但是不能更改私有属性

### 8. 公有属性

定义公有属性：在类中直接定义的，可以提供这个类所属的所有对象都可以访问的属性

In [17]:
class dog(object):
    "dog class"

    nationality = "US"
    
    def __init__(self, name):
        self.name = name

d1 = dog("AAA")
d2 = dog("BBB")
print(d1.nationality, d2.nationality)

US US


#### 访问/修改公有属性

In [19]:
dog.nationality = "CN"
print(dog.nationality)

CN


公有属性不仅可以通过所属类的所有对象访问，还可以通过类本身直接访问和修改

In [21]:
class dog(object):
    "dog class"

    nationality = "US"
    
    def __init__(self, name):
        self.name = name

d1 = dog("AAA")
d2 = dog("BBB")
print(d1.nationality, d2.nationality)
d1.nationality = "CN"
print(d1.nationality, d2.nationality)
dog.nationality = "CN"
print(d1.nationality, d2.nationality)

US US
CN US
CN CN


对象d1去访问nationality属性时，如果在成员属性中找不到，就会找公共属性，也就是说自己的属性找不到就去找父亲的属性。

d1.nationality="CN" 相当于在自己对象内部又重新创建了一个新的局部变量，这个局部变量已经脱离了class本身。

仔细观察我们通过类创建的实例修改的类属性后，通过其他实例访问类属性他的值还是没有改变。其实是通过实例修改类属性是给实例创建了一个与类属性同名的实例属性而已，实例属性访问优先级比类属性高，所以我们访问时优先访问实例属性，它将屏蔽掉对类属性的访问。

## other

### ":"

冒号（：）表示的就是一个整体，冒号出现在哪里就代表这个位置对整体。

双冒号：

- `a[::2]`将 a 中的元素两个两个分组并取每组中第一个出来，也可以理解为每 2 个数中取一个。

- `a[::3]`将 a 中的元素三个三个分组并取每组中第一个出来。

- `a[::-2]`将 a 中元素倒序后两个两个分组并取每组中第一个出来。

In [2]:
import numpy as np
a = np.arange(0, 9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [3]:
print(a[::2])

[0 2 4 6 8]


In [5]:
print(a[::3])

[0 3 6]


In [6]:
print(a[::-1])

[8 7 6 5 4 3 2 1 0]


Ref:

[Python中的排序sorted(d.items(), key=lambda x: x[1])](https://www.cnblogs.com/lyj0123/p/13431972.html)

[python--类的实例化](https://www.cnblogs.com/doumingyi/p/12469120.html)

[Python入门 类class 基础篇](https://zhuanlan.zhihu.com/p/30024792)

[python 中冒号（：）的作用](https://blog.csdn.net/weixin_46813313/article/details/113696218)