# how to use python

## 字符串

### 转义字符

在需要在字符中使用特殊字符时，python 用反斜杠 \ 转义字符。

### Python 字符串格式化

最基本的用法是将一个值插入到一个有字符串格式符 %s 的字符串中。

In [31]:
print("My name is %s and weight is %d kg!" % ('Zara', 21) )

My name is Zara and weight is 21 kg!


python 字符串格式化符号:

- %s 格式化字符串
- %d 格式化整数

### Python 的字符串内建函数

- string.join(seq) 以 string 作为分隔符，将 seq 中所有的元素(的字符串表示)合并为一个新的字符串
- string.lstrip() 截掉 string 左边的空格
- string.split(str="", num=string.count(str)) 以 str 为分隔符切片 string，如果 num 有指定值，则仅分隔 num+1 个子字符串

#### join()

The `join()` method is used to form a string from substrings. The syntax of Python's join() method is:

`<sep>.join(<iterable>)`

- `<iterable>` is any Python iterable containing the substrings, say, a list or a tuple.
- `<sep>` is the separator that you'd like to join the substrings on.

`<sep>.join(<iterable>)` joins substrings in `<iterable>` using `<sep>` as the separator.

In [35]:
my_string = "Apples, Oranges, Pears, Bananas, Berries"
my_list = my_string.split(",")
print(", ".join(my_list))
print("___".join(my_list))

Apples,  Oranges,  Pears,  Bananas,  Berries
Apples___ Oranges___ Pears___ Bananas___ Berries


#### split()

The `split()` method acts on a string and returns a list of substrings. The syntax is:

`<string>.split(sep, maxsplit)`

- sep is an optional argument. By default, this method splits strings on whitespaces.
- maxsplit is an optional argument indicating the number of times you'd like to split <string>.
- maxsplit has a default value of -1, which splits the string on all occurrences of sep.

`<string>.split(sep, maxsplit)` splits `<string>` on the occurrence of sep, maxsplit number of times

In [33]:
my_string = "Apples, Oranges, Pears, Bananas, Berries"
my_string.split(",", 2) # 以，为分隔符，只进行两次split

['Apples', ' Oranges', ' Pears, Bananas, Berries']

## 哈希表、映射、集合

### 哈希表 Hash table

#### 哈希碰撞
- 开放寻址法：产生冲突后继续寻找下一个空闲的空间（没有被占用的存储地址），Python使用的就是这种方法。
- 链地址法：散列到同一位置的元素，不继续往下寻找，而是将所有关键字为同义词的记录存储在同一线性链表中，HashMap就采用了链地址法。
- 再散列函数法：产生冲突后，就再来一次哈希计算，直到没有冲突。
- 建立一个公共溢出区：也就是建两个表，一个作为基本表，另一个是存储和基本表发生冲突元素的溢出表。

#### python字典

在 Python3.7+版本中，字典是有序的。

In [42]:
# 合并字典
mydict1 = {1:"apple",2:"banana"}
mydict2 = {3:"orange"}
mydict1.update(mydict2)
print(mydict1)

# 字典排序
mydict = {1:"apple",3:"banana",2:"orange"}
print(sorted(mydict.items(), key=lambda x: x[0])) # 键，升序
print(sorted(mydict.items(), key=lambda x: x[0], reverse=True)) # 键，降序

{1: 'apple', 2: 'banana', 3: 'orange'}
[(1, 'apple'), (2, 'orange'), (3, 'banana')]
[(3, 'banana'), (2, 'orange'), (1, 'apple')]


### 映射 Map

#### python 映射函数

In [49]:
# 创建映射
res = map(lambda x: x ** 2, [1, 2, 3, 4, 5])
print(list(res))

[1, 4, 9, 16, 25]


### 集合 Set

与列表(list)类似，但集合set没有重复元素，集合没有键和值的配对，是一系列无序的、唯一的元素组合。

字典和集合的内部结构都是一张哈希表，字典存储了哈希值（hash）、键和值这 3 个元素，而集合的哈希表内没有键和值的配对，只有单一的元素。和列表不一样，集合不支持索引操作。

#### python 集合

In [51]:
# 创建集合
setA = {'apple', 'banana'}
print(setA)

# 增加元素
setA.add("orange")
print(setA)

# 删除元素
setA.remove('orange')
print(setA)

# 集合排序
sorted(setA)

{'banana', 'apple'}
{'banana', 'orange', 'apple'}
{'banana', 'apple'}


['apple', 'banana']

## class

### 1. 类的定义和语法

In [8]:
class dog(object): # 用class定义类
    "dog class" # 对类的说明
    
    def __init__(self, name): # 构造函数/构造方法/初始化方法
        self.name = name # 属性/成员变量/字段

    def sayhi(self): # 类方法/动态属性
        "sayhi function" # 对类方法的说明
        print("hello, I am a dog, my name is", self.name)

d = dog("AAA") # 定义一个d的对象（实例）
d.sayhi() # 调用实例的方法

hello, I am a dog, my name is AAA


### 2. self关键字

self相当于实例化对象本身d，在实例化过程中将自身传入

`d = dog(d, "AAA")`

### 3. 函数__init__(), \_\_del__()

在类中__init__()函数叫构造函数，又叫构造方法，也可以叫初始化函数。它的作用就是初始化实例时，初始化传入实例的的默认值。

在类中__del__()函数叫做析构函数，是在实例销毁的时候调用的函数。

### 4. 类的实例化过程图解

· 第一步：先申请一块空间，并命名实例

· 第二步：将地址和赋值参数传给类

· 第三步：生成实例

### 5. 访问类属性

### 6. 修改类属性

In [9]:
class dog(object):
    "dog class"
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def sayhi(self, update_age):
        self.age = update_age

d = dog("AAA", 18)
d.sayhi(19) # 在类的方法中修改
print(d.age)
d.age = 20 # 在类外面修改
print(d.age)

19
20


就是说在类的方法中或者类的外面都可以修改类的属性

### 7. 私有属性

In [13]:
class dog(object):
    "dog class"
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.__sex = "male" # 定义私有属性
    
    def sayhi(self, update_age):
        self.age = update_age

d = dog("AAA", 18)
print(d.__sex)

AttributeError: 'dog' object has no attribute '__sex'

私有属性是不可以访问的，更不可以修改

#### 强制访问/修改私有属性

In [16]:
class dog(object):
    "dog class"
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.__sex = "male" # 定义私有属性
    
    def sayhi(self, update_age):
        self.age = update_age

d = dog("AAA", 18)
print(d._dog__sex)
d._dog__sex = 'female'
print(d._dog__sex)

male
female


这种方法就更为暴力，可以访问也可以修改，就是：对象名._类名__属性名

#### get方法访问私有属性

In [14]:
class dog(object):
    "dog class"
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.__sex = "male"

    def get_sex(self): # 定义get方法
        return self.__sex # 返回

d = dog("AAA", 18)
d_sex = d.get_sex()
print(d_sex)

male


这种方法只能访问私有属性，但是不能更改私有属性

### 8. 公有属性

定义公有属性：在类中直接定义的，可以提供这个类所属的所有对象都可以访问的属性

In [17]:
class dog(object):
    "dog class"

    nationality = "US"
    
    def __init__(self, name):
        self.name = name

d1 = dog("AAA")
d2 = dog("BBB")
print(d1.nationality, d2.nationality)

US US


#### 访问/修改公有属性

In [19]:
dog.nationality = "CN"
print(dog.nationality)

CN


公有属性不仅可以通过所属类的所有对象访问，还可以通过类本身直接访问和修改

In [21]:
class dog(object):
    "dog class"

    nationality = "US"
    
    def __init__(self, name):
        self.name = name

d1 = dog("AAA")
d2 = dog("BBB")
print(d1.nationality, d2.nationality)
d1.nationality = "CN"
print(d1.nationality, d2.nationality)
dog.nationality = "CN"
print(d1.nationality, d2.nationality)

US US
CN US
CN CN


对象d1去访问nationality属性时，如果在成员属性中找不到，就会找公共属性，也就是说自己的属性找不到就去找父亲的属性。

d1.nationality="CN" 相当于在自己对象内部又重新创建了一个新的局部变量，这个局部变量已经脱离了class本身。

仔细观察我们通过类创建的实例修改的类属性后，通过其他实例访问类属性他的值还是没有改变。其实是通过实例修改类属性是给实例创建了一个与类属性同名的实例属性而已，实例属性访问优先级比类属性高，所以我们访问时优先访问实例属性，它将屏蔽掉对类属性的访问。

## other

### lambda

lambda函数没有名字，是一种简单的、在同一行中定义函数的方法。

lambda函数一般功能简单：单行expression决定了lambda函数不可能完成复杂的逻辑，只能完成非常简单的功能。由于其实现的功能一目了然，甚至不需要专门的名字来说明。

lambda 函数可以接收任意多个参数 (包括可选参数) 并且返回单个表达式的值。

lambda表达式只允许包含一个表达式，不能包含复杂语句，该表达式的运算结果就是函数的返回值。

形式 `lambda argument_list:expersion`

In [28]:
# 直接赋给一个变量，然后再像一般函数那样调用
c = lambda x, y, z: x * y * z
print(c(2,3,4))

# 将lambda函数作为参数传递给其他函数比如说结合map、filter、sorted、reduce等一些Python内置函数使用
a=[('b', 3),('a', 2),('d', 4),('c', 1)]
print(sorted(a,key=lambda x:x[0]))

24
[('a', 2), ('b', 3), ('c', 1), ('d', 4)]


### 排序

In [ ]:
# 将字典d按value的值进行排序
d = {'a': 24, 'g': 52, 'i': 12, 'k': 33}
b4 = sorted(d.items(), key=lambda x: x[1])
print(b4) 

"""sorted(d.items(), key=lambda x: x[1])   中 d.items() 为待排序的对象；
key=lambda x: x[1] 为对前面的对象中的第二维数据（即value）的值进行排序。 
key=lambda  变量：变量[维数] 。维数可以按照自己的需要进行设置。"""

# 将列表中的age由大到小排序
alist = [{'name1': 'a', 'age': 20}, {'name2': 'b', 'age': 30}, {'name3': 'c', 'age': 25}]
b = sorted(alist, key=lambda x: x['age'], reverse=True) # reverse 是否逆序
print(b)

[('i', 12), ('a', 24), ('k', 33), ('g', 52)]
[{'name2': 'b', 'age': 30}, {'name3': 'c', 'age': 25}, {'name1': 'a', 'age': 20}]


### collections

#### defaultdict

defaultdict 相比于 dict 的最大区别就是可以设置默认的数值，即便 key 不存在。

In [29]:
from collections import defaultdict
s = [('color', 'blue'), ('color', 'orange'), ('color', 'yellow'), ('fruit', 'banana'), ('fruit', 'orange'),
     ('fruit', 'banana')]
d = defaultdict(list)
for k, v in s:
    d[k].append(v)
print(d) 

defaultdict(<class 'list'>, {'color': ['blue', 'orange', 'yellow'], 'fruit': ['banana', 'orange', 'banana']})


In [30]:
s = [('color', 'blue'), ('color', 'orange'), ('color', 'yellow'), ('fruit', 'banana'), ('fruit', 'orange'),
     ('fruit', 'banana')]
d = defaultdict(set)
for k, v in s:
    d[k].add(v)
print(d)

defaultdict(<class 'set'>, {'color': {'blue', 'yellow', 'orange'}, 'fruit': {'banana', 'orange'}})


#### deque

deque当中最常用也是最核心的api还有append、pop、appendleft和popleft。从名字上我们就看得出来，append和pop和list的append和pop一样，而appendleft和popleft则是在队列左侧，也就是头部进行pop和append的操作。

### ":"

冒号（：）表示的就是一个整体，冒号出现在哪里就代表这个位置对整体。

双冒号：

- `a[::2]`将 a 中的元素两个两个分组并取每组中第一个出来，也可以理解为每 2 个数中取一个。

- `a[::3]`将 a 中的元素三个三个分组并取每组中第一个出来。

- `a[::-2]`将 a 中元素倒序后两个两个分组并取每组中第一个出来。

In [2]:
import numpy as np
a = np.arange(0, 9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [3]:
print(a[::2])

[0 2 4 6 8]


In [5]:
print(a[::3])

[0 3 6]


In [6]:
print(a[::-1])

[8 7 6 5 4 3 2 1 0]


Ref:

[Python 字符串](https://www.runoob.com/python/python-strings.html)

[Python String split() and join() Methods – Explained with Examples](https://www.freecodecamp.org/news/python-string-split-and-join-methods-explained-with-examples/)

[算法笔记：哈希表、映射和集合](https://hiyongz.github.io/posts/algorithm-notes-for-hash-table/)

[python--类的实例化](https://www.cnblogs.com/doumingyi/p/12469120.html)

[Python入门 类class 基础篇](https://zhuanlan.zhihu.com/p/30024792)

[细说Python的lambda函数用法，建议收藏](https://zhuanlan.zhihu.com/p/80960485)

[Python中的排序sorted(d.items(), key=lambda x: x[1])](https://www.cnblogs.com/lyj0123/p/13431972.html)

[[Python技巧]是时候用 defaultdict 和 Counter 代替 dictionary 了](https://cloud.tencent.com/developer/article/1488546)

[Python——详解collections工具库](https://zhuanlan.zhihu.com/p/110476502)

[python 中冒号（：）的作用](https://blog.csdn.net/weixin_46813313/article/details/113696218)