# how to use python

## other

### ":"

冒号（：）表示的就是一个整体，冒号出现在哪里就代表这个位置对整体。

双冒号：

- `a[::2]`将 a 中的元素两个两个分组并取每组中第一个出来，也可以理解为每 2 个数中取一个。

- `a[::3]`将 a 中的元素三个三个分组并取每组中第一个出来。

- `a[::-2]`将 a 中元素倒序后两个两个分组并取每组中第一个出来。

In [2]:
import numpy as np
a = np.arange(0, 9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [3]:
print(a[::2])

[0 2 4 6 8]


In [5]:
print(a[::3])

[0 3 6]


In [6]:
print(a[::-1])

[8 7 6 5 4 3 2 1 0]
